version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: "1"
      KAFKA_LOG_DIRS: /logs
      KAFKA_CREATE_TOPICS: "t_payment_request:10:1,Topic2:5:1,TopicBenchmark:10:1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - ~/workspace/docker/volumes/kafka/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
